### Teste de Endpoints para Pacote

# Consultar todos os pacotes
GET http://localhost:8080/pacotes
Accept: application/json

###

# Adicionar um novo pacote
POST http://localhost:8080/pacotes
Content-Type: application/json

{
  "id": "123456",
  "destinatario": "João Silva",
  "endereco": {
    "rua": "Rua das Flores",
    "numero": "123",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345-678"
  },
  "status": "pendente"
}

###

# Consultar um pacote específico
GET http://localhost:8080/pacotes/123456
Accept: application/json

###

# Atualizar as informações de um pacote
PUT http://localhost:8080/pacotes/123456
Content-Type: application/json

{
  "id": "123456",
  "destinatario": "João Silva",
  "endereco": {
    "rua": "Rua das Flores",
    "numero": "123",
    "cidade": "São Paulo",
    "estado": "SP",
    "cep": "12345-678"
  },
  "status": "em trânsito"
}

###

# Remover um pacote
DELETE http://localhost:8080/pacotes/123456

### Teste de Endpoints para Rastreamento

# Adicionar um novo rastreamento
POST http://localhost:8080/rastreamentos
Content-Type: application/json

{
  "dataHora": "2024-08-01T12:00:00",
  "status": "em trânsito",
  "localizacao": "Centro de Distribuição",
  "pacote": {
    "id": "123456"
  }
}

###

# Consultar todos os rastreamentos de um pacote específico
GET http://localhost:8080/rastreamentos/123456
Accept: application/json

### Teste de Endpoints para Endereco

# Consultar todos os endereços
GET http://localhost:8080/enderecos
Accept: application/json

###

# Adicionar um novo endereço
POST http://localhost:8080/enderecos
Content-Type: application/json

{
  "rua": "Rua das Flores",
  "numero": "123",
  "cidade": "São Paulo",
  "estado": "SP",
  "cep": "12345-678"
}
